<?xml version="1.0"?>
<!-- Simple 3-Revolute Arm -->
<!--
Reference and modified from ros2_control_demos 
https://github.com/ros-controls/ros2_control_demos
-->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="simple_3r_arm" params="parent prefix *origin">

    <!-- Constants for robot dimensions -->
    <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
    <xacro:property name="lengthBase" value="2" /> <!-- Base Link -->
    <xacro:property name="length1" value="1" /> <!-- Link 1 -->
    <xacro:property name="length2" value="1" /> <!-- Link 2 -->
    <xacro:property name="length3" value="1" /> <!-- Link 3 -->
    <xacro:property name="width" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
    <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

    <!-- Base Link -->
    <joint name="${prefix}base_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${prefix}base_link" />
    </joint>
    <link name="${prefix}base_link">
      <collision>
        <origin xyz="0 0 ${lengthBase/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${width} ${width} ${lengthBase}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 ${lengthBase/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${width} ${width} ${lengthBase}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <inertial>
        <origin xyz="0 0 ${lengthBase/2}" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia ixx="${mass / 12.0 * (width*width + lengthBase*lengthBase)}" ixy="0.0" ixz="0.0" 
                 iyy="${mass / 12.0 * (lengthBase*lengthBase + width*width)}" iyz="0.0"
                 izz="${mass / 12.0 * (width*width + width*width)}"/>
      </inertial>
    </link>

    <!-- Link 1 -->
    <joint name="${prefix}joint1" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}link1"/>
      <origin xyz="0 0 ${lengthBase}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.7"/>
    </joint>
    <link name="${prefix}link1">
      <collision>
        <origin xyz="0 0 ${length1/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${width} ${width} ${length1}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 ${length1/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${width} ${width} ${length1}"/>
        </geometry>
        <material name="orange"/>
      </visual>

      <inertial>
        <origin xyz="0 0 ${length1/2}" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia ixx="${mass / 12.0 * (width*width + length1*length1)}" ixy="0.0" ixz="0.0"
                 iyy="${mass / 12.0 * (length1*length1 + width*width)}" iyz="0.0"
                 izz="${mass / 12.0 * (width*width + width*width)}"/>
      </inertial>
    </link>

    <!-- Link 2 -->
    <joint name="${prefix}joint2" type="continuous">
      <parent link="${prefix}link1"/>
      <child link="${prefix}link2"/>
      <origin xyz="0 ${width} ${length1}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.7"/>
    </joint>
    <link name="${prefix}link2">
      <collision>
        <origin xyz="${length2/2} 0 0" rpy="0 ${pi/2} 0"/>
        <geometry>
          <box size="${width} ${width} ${length2}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="${length2/2} 0 0" rpy="0 ${pi/2} 0"/>
        <geometry>
          <box size="${width} ${width} ${length2}"/>
        </geometry>
        <material name="yellow"/>
      </visual>

      <inertial>
        <origin xyz="${length2/2} 0 0" rpy="0 ${pi/2} 0"/>
        <mass value="${mass}"/>
        <inertia ixx="${mass / 12.0 * (width*width + length2*length2)}" ixy="0.0" ixz="0.0"
                 iyy="${mass / 12.0 * (length2*length2 + width*width)}" iyz="0.0"
                 izz="${mass / 12.0 * (width*width + width*width)}"/>
      </inertial>
    </link>

    <!-- Link 3 -->
    <joint name="${prefix}joint3" type="continuous">
      <parent link="${prefix}link2"/>
      <child link="${prefix}link3"/>
      <origin xyz="${length2} -${width} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.7"/>
    </joint>
    <link name="${prefix}link3">
      <collision>
        <origin xyz="${length3/2} 0 0" rpy="0 ${pi/2} 0"/>
        <geometry>
          <box size="${width} -${width} ${length3}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="${length3/2} 0 0" rpy="0 ${pi/2} 0"/>
        <geometry>
          <box size="${width} -${width} ${length3}"/>
        </geometry>
        <material name="green"/>
      </visual>

      <inertial>
        <origin xyz="${length3/2} 0 0" rpy="0 ${pi/2} 0"/>
        <mass value="${mass}"/>
        <inertia ixx="${mass / 12.0 * (width*width + length3*length3)}" ixy="0.0" ixz="0.0"
                 iyy="${mass / 12.0 * (length3*length3 + width*width)}" iyz="0.0"
                 izz="${mass / 12.0 * (width*width + width*width)}"/>
      </inertial>
    </link>

    <!-- Tool Link -->
    <joint name="${prefix}tool_joint" type="fixed">
      <origin xyz="0 0 1" rpy="0 0 0" />
      <parent link="${prefix}link3"/>
      <child link="${prefix}tool_link" />
    </joint>
    <link name="${prefix}tool_link">
    </link>

  </xacro:macro>

</robot>
